name: Metrics
on:
  schedule:
    - cron: "7 0 * * *" # daily
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }} # PAT classic: repo, read:user
          base: header, repositories
          template: classic
          config_timezone: Asia/Dhaka

          # Popular modules
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 1%
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_stargazers: yes
          plugin_activity: yes
          plugin_lines: yes

          # Output
          filename: github-metrics.svg
