name: GitHub Metrics

on:
  schedule: [{ cron: "0 */12 * * *" }]  # every 12 hours
  workflow_dispatch:

permissions:
  contents: write  # needed to commit the SVG

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Render metrics and commit
        uses: lowlighter/metrics@v3.34
        with:
          # Who to render
          user: shakilkhan496

          # Tokens
          token: ${{ secrets.GH_TOKEN }}            # <-- your PAT (classic), NOT GITHUB_TOKEN
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Output (commit to main)
          filename: github-metrics.svg
          output_action: commit
          committer_branch: main
          committer_message: "chore: update github-metrics.svg [skip ci]"

          # Look & data
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Dhaka

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_stargazers: yes
          plugin_achievements: yes
          plugin_lines: yes
