name: Update YTD GitHub Stats

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "17 0 * * *"  # runs 00:17 UTC ≈ 06:17 Asia/Dhaka
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ytd:
    runs-on: ubuntu-latest
    env:
      LOGIN: shakilkhan496
      # Add these after you create them:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}   # your PAT (classic) with gist + read:user
      GIST_ID: GIST_ID_HERE               # <-- replace with your actual Gist ID
    steps:
      - name: Compute current-year stats (GraphQL)
        id: stats
        uses: actions/github-script@v7
        with:
          # Falls back to GITHUB_TOKEN so the job still runs even if GH_TOKEN is empty
          github-token: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
          script: |
            const year = new Date().getUTCFullYear();
            const from = `${year}-01-01T00:00:00Z`;
            const to = new Date().toISOString();
            const query = `
              query($login:String!, $from:DateTime!, $to:DateTime!) {
                user(login: $login) {
                  contributionsCollection(from: $from, to: $to) {
                    totalCommitContributions
                    restrictedContributionsCount
                    contributionCalendar { totalContributions }
                  }
                }
              }
            `;
            const variables = { login: process.env.LOGIN, from, to };
            const res = await github.graphql(query, variables);
            const c = res.user.contributionsCollection;
            const commits = c?.totalCommitContributions ?? 0;
            const publicCal = c?.contributionCalendar?.totalContributions ?? 0;
            const restricted = c?.restrictedContributionsCount ?? 0;
            const contribs = publicCal + restricted;
            core.setOutput("commits", String(commits));
            core.setOutput("contribs", String(contribs));

      - name: Show YTD numbers in job summary
        run: |
          {
            echo "### YTD Stats";
            echo "";
            echo "- Commits (YTD): ${{ steps.stats.outputs.commits }}";
            echo "- Contributions (YTD, incl. private if PAT present): ${{ steps.stats.outputs.contribs }}";
          } >> "$GITHUB_STEP_SUMMARY"

      # Update badges only if both PAT and Gist ID are present
      - name: Update badge — Commits (YTD)
        if: ${{ env.GH_TOKEN != '' && env.GIST_ID != '' }}
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ env.GH_TOKEN }}   # must include 'gist' scope
          gistID: ${{ env.GIST_ID }}
          filename: commits.json
          label: Commits (YTD)
          message: ${{ steps.stats.outputs.commits }}
          color: blue

      - name: Update badge — Contributions (YTD)
        if: ${{ env.GH_TOKEN != '' && env.GIST_ID != '' }}
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ env.GH_TOKEN }}
          gistID: ${{ env.GIST_ID }}
          filename: contributions.json
          label: Contributions (YTD)
          message: ${{ steps.stats.outputs.contribs }}
          color: orange
