name: Update YTD GitHub Stats

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "17 0 * * *"  # ~06:17 Asia/Dhaka
  workflow_dispatch:

jobs:
  ytd:
    runs-on: ubuntu-latest

    steps:
      - name: Compute current-year stats via GraphQL
        id: stats
        uses: actions/github-script@v7
        with:
          # Use your own PAT so private activity counts; must have: repo, read:user, gist
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const year = new Date().getUTCFullYear();
            const from = `${year}-01-01T00:00:00Z`;
            const to = new Date().toISOString();
            const variables = { login: "shakilkhan496", from, to };
            const query = `
              query($login:String!, $from:DateTime!, $to:DateTime!) {
                user(login: $login) {
                  contributionsCollection(from: $from, to: $to) {
                    totalCommitContributions
                    restrictedContributionsCount
                    contributionCalendar { totalContributions }
                  }
                }
              }
            `;
            const res = await github.graphql(query, variables);
            const coll = res.user.contributionsCollection;
            const commits = coll.totalCommitContributions ?? 0;
            const contribs = (coll.contributionCalendar?.totalContributions ?? 0) + (coll.restrictedContributionsCount ?? 0);
            core.setOutput("commits", String(commits));
            core.setOutput("contribs", String(contribs));

      - name: Update badge - Commits (YTD)
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GH_TOKEN }}     # PAT needs 'gist' scope
          gistID: GIST_ID_HERE              # <-- replace with your Gist ID
          filename: commits.json
          label: Commits (YTD)
          message: ${{ steps.stats.outputs.commits }}
          color: blue

      - name: Update badge - Contributions (YTD)
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GH_TOKEN }}
          gistID: GIST_ID_HERE              # <-- replace with your Gist ID
          filename: contributions.json
          label: Contributions (YTD)
          message: ${{ steps.stats.outputs.contribs }}
          color: orange
