name: Update YTD GitHub Stats

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "17 0 * * *"  # ~06:17 Asia/Dhaka (UTC+6)
  workflow_dispatch:

jobs:
  ytd:
    runs-on: ubuntu-latest
    steps:
      - name: Compute current-year stats (GraphQL)
        id: stats
        uses: actions/github-script@v7
        with:
          # Fallback: if GH_TOKEN isn't set, use the built-in GITHUB_TOKEN
          github-token: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
          script: |
            const year = new Date().getUTCFullYear();
            const from = `${year}-01-01T00:00:00Z`;
            const to = new Date().toISOString();
            const query = `
              query($login:String!, $from:DateTime!, $to:DateTime!) {
                user(login: $login) {
                  contributionsCollection(from: $from, to: $to) {
                    totalCommitContributions
                    restrictedContributionsCount
                    contributionCalendar { totalContributions }
                  }
                }
              }
            `;
            const variables = { login: "shakilkhan496", from, to };
            const res = await github.graphql(query, variables);
            const c = res.user.contributionsCollection;
            const commits = c?.totalCommitContributions ?? 0;
            const publicCalendar = c?.contributionCalendar?.totalContributions ?? 0;
            const restricted = c?.restrictedContributionsCount ?? 0;
            const totalContribs = publicCalendar + restricted;

            core.setOutput("commits", String(commits));
            core.setOutput("contribs", String(totalContribs));

      - name: Show YTD numbers in job summary
        run: |
          {
            echo "### YTD Stats";
            echo "";
            echo "- Commits (YTD): ${{ steps.stats.outputs.commits }}";
            echo "- Contributions (YTD, incl. private if available): ${{ steps.stats.outputs.contribs }}";
          } >> "$GITHUB_STEP_SUMMARY"

      # These two steps require a personal token with 'gist' scope.
      # They are skipped automatically if GH_TOKEN is not set.
      - name: Update badge — Commits (YTD)
        if: ${{ secrets.GH_TOKEN != '' }}
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GH_TOKEN }}     # PAT must include 'gist'
          gistID: GIST_ID_HERE              # <-- replace with your Gist ID
          filename: commits.json
          label: Commits (YTD)
          message: ${{ steps.stats.outputs.commits }}
          color: blue

      - name: Update badge — Contributions (YTD)
        if: ${{ secrets.GH_TOKEN != '' }}
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GH_TOKEN }}
          gistID: GIST_ID_HERE              # <-- replace with your Gist ID
          filename: contributions.json
          label: Contributions (YTD)
          message: ${{ steps.stats.outputs.contribs }}
          color: orange
